// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email,password_hash,full_name)
VALUES ($1,$2,$3)
RETURNING id, email, full_name, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FullName     string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	FullName  string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, password_hash
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Email        string
	FullName     string
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, created_at, updated_at, email, password_hash, full_name, reset_token, reset_token_expires FROM users
WHERE reset_token = $1 AND reset_token_expires > NOW()
`

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByResetToken, resetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ResetToken,
		&i.ResetTokenExpires,
	)
	return i, err
}

const setResetToken = `-- name: SetResetToken :exec
UPDATE users
SET reset_token = $2, reset_token_expires = $3
WHERE email = $1
`

type SetResetTokenParams struct {
	Email             string
	ResetToken        sql.NullString
	ResetTokenExpires sql.NullTime
}

func (q *Queries) SetResetToken(ctx context.Context, arg SetResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, setResetToken, arg.Email, arg.ResetToken, arg.ResetTokenExpires)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2, 
  reset_token = NULL, 
  reset_token_expires = NULL, 
  updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
